theme: jekyll-theme-slate
title: Stanford Middle East Ensemble
description: A community ensemble based at Stanford University dedicated to teaching and performing music from across the Middle East. Join us!
show_downloads: false
google_analytics: UA-134144171-1
